overrides:
  ioredis: 5.11.1

allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
