import type { ArabicEntity } from "@/lib/types/content";

export const mockArabicEntities: ArabicEntity[] = [
  {
    id: "1",
    entityKey: "AE-1024",
    arabicText: "مرحبا",
    normalizedText: "مرحبا",
    meaningBangla: "হ্যালো / স্বাগতম",
    meaningEnglish: "Hello / Welcome",
    pronunciationBangla: "মারহাবান",
    pronunciationEnglish: "Marhaban",
    hasAudio: true,
    audioUrl: "/audio/ae-1024.mp3",
    status: "PUBLISHED",
    wordUsageCount: 3,
    sentenceUsageCount: 5,
    conversationUsageCount: 2,
    createdBy: "Rahim Ahmed",
    createdAt: "2026-06-02T09:12:00Z",
    updatedAt: "2026-09-08T14:20:00Z",
  },
  {
    id: "2",
    entityKey: "AE-1025",
    arabicText: "مرحباً بك",
    normalizedText: "مرحبا بك",
    meaningBangla: "স্বাগতম",
    meaningEnglish: "Welcome",
    pronunciationBangla: "মারহাবান বিক",
    pronunciationEnglish: "Marhaban bik",
    hasAudio: true,
    audioUrl: "/audio/ae-1025.mp3",
    status: "PUBLISHED",
    wordUsageCount: 0,
    sentenceUsageCount: 1,
    conversationUsageCount: 0,
    createdBy: "Rahim Ahmed",
    createdAt: "2026-06-03T10:00:00Z",
    updatedAt: "2026-08-20T11:00:00Z",
  },
  {
    id: "3",
    entityKey: "AE-1032",
    arabicText: "كم السعر؟",
    normalizedText: "كم السعر",
    meaningBangla: "দাম কত?",
    meaningEnglish: "How much is it?",
    pronunciationBangla: "কাম আস-সি'র",
    pronunciationEnglish: "Kam as-si'r?",
    hasAudio: true,
    audioUrl: "/audio/ae-1032.mp3",
    status: "PUBLISHED",
    wordUsageCount: 0,
    sentenceUsageCount: 4,
    conversationUsageCount: 3,
    createdBy: "Nusrat Jahan",
    createdAt: "2026-06-10T08:30:00Z",
    updatedAt: "2026-09-01T16:45:00Z",
  },
  {
    id: "4",
    entityKey: "AE-1033",
    arabicText: "أريد هذا",
    normalizedText: "اريد هذا",
    meaningBangla: "আমি এটা চাই",
    meaningEnglish: "I want this",
    pronunciationBangla: "উরিদু হাযা",
    pronunciationEnglish: "Ureedu haza",
    hasAudio: false,
    status: "IN_REVIEW",
    wordUsageCount: 0,
    sentenceUsageCount: 2,
    conversationUsageCount: 1,
    createdBy: "Nusrat Jahan",
    createdAt: "2026-08-28T12:00:00Z",
    updatedAt: "2026-09-09T09:10:00Z",
  },
  {
    id: "5",
    entityKey: "AE-1041",
    arabicText: "شكراً",
    normalizedText: "شكرا",
    meaningBangla: "ধন্যবাদ",
    meaningEnglish: "Thank you",
    pronunciationBangla: "শুকরান",
    pronunciationEnglish: "Shukran",
    hasAudio: true,
    audioUrl: "/audio/ae-1041.mp3",
    status: "PUBLISHED",
    wordUsageCount: 2,
    sentenceUsageCount: 6,
    conversationUsageCount: 5,
    createdBy: "Rahim Ahmed",
    createdAt: "2026-06-15T09:00:00Z",
    updatedAt: "2026-09-05T13:30:00Z",
  },
  {
    id: "6",
    entityKey: "AE-1058",
    arabicText: "أين الحمام؟",
    normalizedText: "اين الحمام",
    meaningBangla: "টয়লেট কোথায়?",
    meaningEnglish: "Where is the bathroom?",
    pronunciationBangla: "আইনাল হাম্মাম",
    pronunciationEnglish: "Aynal hammam?",
    hasAudio: false,
    status: "DRAFT",
    wordUsageCount: 0,
    sentenceUsageCount: 1,
    conversationUsageCount: 0,
    createdBy: "Nusrat Jahan",
    createdAt: "2026-09-07T10:00:00Z",
    updatedAt: "2026-09-07T10:00:00Z",
  },
  {
    id: "7",
    entityKey: "AE-1060",
    arabicText: "بكم هذا؟",
    normalizedText: "بكم هذا",
    meaningBangla: "এটার দাম কত?",
    meaningEnglish: "How much is this?",
    pronunciationBangla: "বিকাম হাযা",
    pronunciationEnglish: "Bikam haza?",
    hasAudio: false,
    status: "REJECTED",
    rejectionReason:
      "English pronunciation needs correction — should be closer to 'bi-kam' with a short pause.",
    wordUsageCount: 0,
    sentenceUsageCount: 1,
    conversationUsageCount: 0,
    createdBy: "Nusrat Jahan",
    createdAt: "2026-09-02T09:00:00Z",
    updatedAt: "2026-09-06T15:00:00Z",
  },
  {
    id: "8",
    entityKey: "AE-1002",
    arabicText: "رخيص",
    normalizedText: "رخيص",
    meaningBangla: "সস্তা",
    meaningEnglish: "Cheap",
    pronunciationBangla: "রাখিস",
    pronunciationEnglish: "Rakhees",
    hasAudio: true,
    audioUrl: "/audio/ae-1002.mp3",
    status: "PUBLISHED",
    wordUsageCount: 1,
    sentenceUsageCount: 3,
    conversationUsageCount: 1,
    createdBy: "Rahim Ahmed",
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-08-11T09:00:00Z",
  },
];

export function findSimilarEntities(arabicText: string): ArabicEntity[] {
  const needle = arabicText.trim().replace(/[\u064B-\u065F\u0670]/g, "");
  if (!needle) return [];
  return mockArabicEntities.filter((entity) =>
    entity.normalizedText.includes(needle.replace(/[إأآ]/g, "ا")),
  );
}
