import type { Sentence } from "@/lib/types/content";
import { mockArabicEntities } from "@/lib/mock-data/arabic-entities";

function entity(id: string) {
    const found = mockArabicEntities.find((e) => e.id === id);
    if (!found) throw new Error(`mock sentence references missing entity id ${id}`);
    return found;
}

export const mockSentences: Sentence[] = [
    {
        id: "s1",
        sentenceKey: "SNT-1024",
        entityId: entity("3").id, // كم السعر؟
        arabicText: entity("3").arabicText,
        meaningBangla: "দাম কত?",
        meaningEnglish: "How much is it?",
        pronunciationBangla: "কাম আস-সি'র",
        pronunciationEnglish: "Kam as-si'r?",
        context: "Asking the price of an item in a shop or market",
        difficulty: "BEGINNER",
        category: "Shopping",
        usedInLessons: 4,
        usedInConversations: 3,
        status: "PUBLISHED",
        createdBy: "Rahim Ahmed",
        createdAt: "2026-06-11T08:30:00Z",
        updatedAt: "2026-09-01T16:45:00Z",
    },
    {
        id: "s2",
        sentenceKey: "SNT-1025",
        entityId: entity("7").id, // بكم هذا؟
        arabicText: entity("7").arabicText,
        meaningBangla: "এটার দাম কত?",
        meaningEnglish: "How much is this?",
        pronunciationBangla: "বিকাম হাযা",
        pronunciationEnglish: "Bikam haza?",
        context: "Asking the price while pointing at a specific item",
        difficulty: "BEGINNER",
        category: "Shopping",
        relatedWordId: "w5",
        usedInLessons: 1,
        usedInConversations: 0,
        status: "REJECTED",
        rejectionReason:
            "English pronunciation needs correction — should be closer to 'bi-kam' with a short pause.",
        createdBy: "Nusrat Jahan",
        createdAt: "2026-09-03T09:00:00Z",
        updatedAt: "2026-09-06T15:00:00Z",
    },
    {
        id: "s3",
        sentenceKey: "SNT-1030",
        entityId: entity("4").id, // أريد هذا
        arabicText: entity("4").arabicText,
        meaningBangla: "আমি এটা চাই",
        meaningEnglish: "I want this",
        pronunciationBangla: "উরিদু হাযা",
        pronunciationEnglish: "Ureedu haza",
        context: "Telling a shopkeeper which item you'd like to buy",
        difficulty: "BEGINNER",
        category: "Shopping",
        relatedWordId: "w4",
        usedInLessons: 2,
        usedInConversations: 1,
        status: "IN_REVIEW",
        createdBy: "Nusrat Jahan",
        createdAt: "2026-08-30T12:00:00Z",
        updatedAt: "2026-09-09T09:10:00Z",
    },
    {
        id: "s4",
        sentenceKey: "SNT-1041",
        entityId: entity("5").id, // شكراً
        arabicText: entity("5").arabicText,
        meaningBangla: "ধন্যবাদ, বিদায়",
        meaningEnglish: "Thank you, goodbye",
        pronunciationBangla: "শুকরান, মাআ সালামা",
        pronunciationEnglish: "Shukran, ma'a salama",
        context: "Closing a friendly interaction, e.g. after a shop visit",
        difficulty: "BEGINNER",
        category: "Greetings",
        relatedWordId: "w1",
        usedInLessons: 3,
        usedInConversations: 5,
        status: "PUBLISHED",
        createdBy: "Rahim Ahmed",
        createdAt: "2026-06-17T09:00:00Z",
        updatedAt: "2026-09-05T13:30:00Z",
    },
    {
        id: "s5",
        sentenceKey: "SNT-1058",
        entityId: entity("6").id, // أين الحمام؟
        arabicText: entity("6").arabicText,
        meaningBangla: "টয়লেট কোথায়?",
        meaningEnglish: "Where is the bathroom?",
        pronunciationBangla: "আইনাল হাম্মাম",
        pronunciationEnglish: "Aynal hammam?",
        context: "Asking for directions to a bathroom in a restaurant",
        difficulty: "BEGINNER",
        category: "Restaurant",
        relatedWordId: "w6",
        usedInLessons: 1,
        usedInConversations: 0,
        status: "DRAFT",
        createdBy: "Nusrat Jahan",
        createdAt: "2026-09-07T11:00:00Z",
        updatedAt: "2026-09-07T11:00:00Z",
    },
    {
        id: "s6",
        sentenceKey: "SNT-1002",
        entityId: entity("8").id, // رخيص
        arabicText: entity("8").arabicText,
        meaningBangla: "এটা কি একটু সস্তা করা যাবে?",
        meaningEnglish: "Can you make it a bit cheaper?",
        pronunciationBangla: "হাল ইউমকিন আন তাখাফফিদ আস-সি'র",
        pronunciationEnglish: "Hal yumkin an tukhaffid as-si'r?",
        context: "Politely negotiating a lower price while shopping",
        difficulty: "ELEMENTARY",
        category: "Shopping",
        relatedWordId: "w2",
        usedInLessons: 2,
        usedInConversations: 1,
        status: "PUBLISHED",
        createdBy: "Rahim Ahmed",
        createdAt: "2026-05-22T09:00:00Z",
        updatedAt: "2026-08-12T09:00:00Z",
    },
];